Rails.application.routes.draw do
  root :to => 'pages#index'
  get 'pages/index'
  get 'pages/gallary'
  get 'pages/contact'
  get 'pages/prize'
  get 'questions/one'
  get 'questions/two'
  get 'questions/three'
  get 'questions/four'
  get 'questions/five'
  get 'questions/six'
  get 'questions/seven'
  get 'questions/eight'
  get 'questions/nine'
  get 'questions/ten'
end
